[package]
name = "fly-migrate"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fly"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.0", features = [ "derive" ] }
dotenv = "0.15.0"
postgres = "0.19.4"
